server {
    listen 80;

    # Backend Health Check
    location = /health {
        proxy_pass http://backend:8000/health;
    }

    # FastAPI Swagger/OpenAPI
    location = /openapi.json {
        proxy_pass http://backend:8000/openapi.json;
    }

    location /api/ {
        proxy_pass http://backend:8000/;
    }

    # WebSocket
    location /ws/ {
        proxy_pass http://backend:8000/ws/;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
    }

    # React frontend
    location / {
        proxy_pass http://frontend:80;
    }
}